### PR TITLE
Issue7: Add a toml file for traefik routing

### PR DESCRIPTION
**Pull request by GeorgianaElena**

### CODE REVIEW

**Comment by GeorgianaElena** [comment]
Hi @minrk! I've just added the test. Ideally the toml file should also be generated from script so that we have the hardcoded ports in only one place (i.e. traefikUtils.py). If you find it necessary at this point, let me know.

**Comment by minrk** [comment]
This is great! I was able to download and run the test. This will be a hugely useful reference.

Would you like to try to get tests running automatically on travis?

**Comment by GeorgianaElena** [comment]
Yay! That's awesome!

Do you mean setting up travis to pick up the tests for this repo? I haven't done that much work with travis, but I could definitely give it a try.

**Comment by minrk** [comment]
If you'd like to give setting up Travis a go, that would be great! You might want to start [with these docs](https://docs.travis-ci.com/user/languages/python/).

The tests should:

in `install`:
1. install pytest to run the tests
2. download and unpack the traefik binary for linux and put it on PATH (e.g. at /usr/local/bin/traefik)

in `script`:

1. run the test with pytest

**Comment by minrk** [comment]
Also, a less important issue: The Python community has a rough style guide called [pep 8](https://www.python.org/dev/peps/pep-0008), which include some things like using `snake_case` instead of `camelCase`. It might be worth a read to get a sense of idiomatic Python code. In Jupyter, we try not to be strict about these things, but it's a good guideline.

When creating new files, you can also avoid a lot of style headaches by using an auto-formatter like [black](https://pypi.org/project/black/) to write code however you want and auto-format it after the fact. This does't cover things like variable names, though.

**Comment by GeorgianaElena** [comment]
Thanks a lot for the feedback. I usually just try to be consistent within the code I write and with the code around me, but I agree with you, if we would all follow a standard the code would be much easier to follow in general.
Didn’t know about that code formatter, it's quite nice, thanks.

**Pull request merged**
