### PR TITLE
Use PyScript to read and display CSV file in-browser

### LINKED ISSUE #157: Automatically update tables of issues in docs, outside of sphinx build
For keeping the table data updated, could we store it somewhere and use the issue open/closed/labeled events to trigger updates on CI? I've seen folks store such data in gists (used [here](https://github.com/finsberg/fenicsx-pulse/blob/1b6baaeef8478a378870d56adaec4b376691fa09/.github/workflows/test_package_coverage.yml#L36-L42), relevant part of the action defined [here](https://github.com/Schneegans/dynamic-badges-action/blob/b7809ee0afb85d93b3cf9b9fa94982ed038312a4/index.js#L178-L189)). That should avoid cron issues. We would still need to do table-data->page table in js instead of during sphinx build.

_Originally posted by @minrk in https://github.com/jupyterhub/outreachy/issues/155#issuecomment-1384051158_

### PR DESCRIPTION
**Pull request by sgibson91**
This is an attempt to use PyScript to perform in-browser Python that reads in a CSV file from a URL and display it. This means we no longer need to depend on the sphinx site build to keep the table up-to-date on the site with the truth in the CSV file source.

This technically works, but aesthetically looks naff and the hyperlinks to the issues don't work. So need some further exploration since the DataTables JavaScript module no longer seems to work.

fix #157 

Screenshot 2023-02-23 at 17 12 50

Link to rendered page: https://jupyterhub-outreachy--191.org.readthedocs.build/en/191/mentors/project-list.html

### CODE REVIEW

**Comment by minrk** [comment]
(*looks up naff*) Cool! This is my first time seeing pyscript actually being used. For datatable, could it be a race?

1. page ready
2. datatable trigger, finds empty table so nothing to do
3. pyscript finishes load, populates raw table

Maybe the datatable invocation needs to trigger via pyscript after `display`? e.g. replace `$(document).on...` with a `function renderTable() {` and call it after the HTML is populated:

```python
import js
...
display(...)
js.renderTable()
```

**Comment by sgibson91** [comment]
I wondered if this section of the PyScript docs would be relevant: https://docs.pyscript.net/latest/guides/passing-objects.html#javascript-to-pyscript So I _think_ instead of using `display`, we could hand the JS object direct to the JS function that is using DataTables. However, I got `AttributeError: createObject` for the `js.createObject(...)` line

**Comment by minrk** [comment]
The `js.renderTable` approach [seems to work](https://github.com/minrk/outreachy/commit/f776309f430eab21f9857f79f7cf103b6b749ad9) when I try it - keep `display` the same, then call your js function when it completes. I don't know enough about the interactions to say why one might work while the other doesn't.

**Comment by sgibson91** [comment]
I'm going to call this good enough for now

**Pull request merged**
